spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.opengauss.Driver
    url: jdbc:opengauss://PROD_HOST:5432/bosz?currentSchema=as_agent&characterEncoding=UTF-8
    username: PROD_USER
    password: PROD_PASSWORD
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 50
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: true

logging:
  level:
    com.suzhou.bank: WARN
