server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: bosz-agent-backend

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.suzhou.bank.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

know-kit:
  base-url: http://localhost:9000
  analyze-path: /api/v1/analyze
  timeout: 300000
