-- =====================================================================
-- 表结构「缺列」自检（一次列全，不用逐列补）
-- 生成来源：仓库 DDL（9 个文件）→ 期望列清单
-- 生成时间：2026-09-21 SALESLOANRATIO
--
-- 🔴 为什么要这个：PG/openGauss 报「column X does not exist」时**只报第一个**失败列，
--    补一个再跑又炸下一个。本脚本把 DDL 里的期望列全部摊平，一次列出**所有**缺失列。
--
-- 用法：整段执行（纯查询，不写库）。结果集 = 缺列清单；空结果 = 结构齐了。
-- ⚠️ 表名/列名统一按小写比对（本项目这些表建表时未加引号 ⇒ 物理列名已折小写）。
-- ⚠️ 只查**当前 schema**（current_schema）；若表在别的 schema，先 SET search_path。
-- =====================================================================

-- 执行前置：SET search_path = <你的 schema>, public;

-- ---------------------------------------------------------------------
-- 结果集 ①：整张表都不存在（先把这类排掉，否则它的列会被全量报成"缺失"，误报）
-- ---------------------------------------------------------------------
WITH expected_tbl(tbl) AS (VALUES
  ('app_capital_flow_info'),
  ('app_check_index_info'),
  ('app_check_object_info'),
  ('app_check_opinion_info'),
  ('app_check_record_info'),
  ('app_collateral_info'),
  ('app_collateral_mortgage_info'),
  ('app_collateral_restricted_right'),
  ('app_credit_approval_manage_req_info'),
  ('app_credit_debt_detail'),
  ('app_credit_query_info'),
  ('app_credit_report_info'),
  ('app_credit_use_info'),
  ('app_customer_info'),
  ('app_early_warning_info'),
  ('app_early_warning_opinion_info'),
  ('app_early_warning_signal_info'),
  ('app_entrust_pay_info'),
  ('app_finance_index_info'),
  ('app_finance_indicator_info'),
  ('app_finance_report_info'),
  ('app_graph_hit_info'),
  ('app_gs_finance_data_info'),
  ('app_gs_tax_sales_info'),
  ('app_guarantor_credit_info'),
  ('app_guarantor_info'),
  ('app_guofa_report_info'),
  ('app_ic_info'),
  ('app_ic_shareholder_info'),
  ('app_loan_plan_info'),
  ('app_loan_receipt_info'),
  ('app_opinion_info'),
  ('app_payroll_stat_info'),
  ('app_report_info'),
  ('app_reputation_event_info'),
  ('app_settle_account_info'),
  ('app_settle_asset_info'),
  ('app_settle_counterparty_info'),
  ('app_shareholder_info'),
  ('app_single_check_task_info'),
  ('app_specific_loan_check_info'),
  ('app_specific_loan_operate_check_info'),
  ('app_specific_loan_project_check_info'),
  ('app_top_five_updown_info'),
  ('app_xd_shareholder_info'),
  ('report'),
  ('app_report_catalog'),
  ('app_report_content_block'),
  ('app_report_content_instance'),
  ('app_report_ai_risk'),
  ('app_report_ai_analysis'),
  ('app_report_prompt'),
  ('app_report_warning_advice_batch'),
  ('app_report_warning_advice'),
  ('app_report_risk_edit_log')
)
SELECT e.tbl AS "缺失的表"
  FROM expected_tbl e
  LEFT JOIN information_schema.tables t
    ON lower(t.table_name) = e.tbl
   AND t.table_schema = current_schema()
 WHERE t.table_name IS NULL
 ORDER BY 1;

-- 📌 若这里出现 app_report_info：**属预期** —— 该表已废弃，报告主表统一以 report 为准。

-- ---------------------------------------------------------------------
-- 结果集 ②：表在、但有缺列（这才是真正要补的）
-- ---------------------------------------------------------------------
WITH expected(tbl, col) AS (VALUES
  ('app_capital_flow_info', 'id'),
  ('app_capital_flow_info', 'reportno'),
  ('app_capital_flow_info', 'customerid'),
  ('app_capital_flow_info', 'customername'),
  ('app_capital_flow_info', 'loanserialno'),
  ('app_capital_flow_info', 'serialno'),
  ('app_capital_flow_info', 'capitalchecktasktype'),
  ('app_capital_flow_info', 'approvestatus'),
  ('app_capital_flow_info', 'ispurposeabnormal'),
  ('app_capital_flow_info', 'rectificationsituation'),
  ('app_capital_flow_info', 'rectificationdeadline'),
  ('app_capital_flow_info', 'rectificationexplanation'),
  ('app_capital_flow_info', 'identifyreason'),
  ('app_capital_flow_info', 'inputtime'),
  ('app_capital_flow_info', 'loanstatus'),
  ('app_check_index_info', 'id'),
  ('app_check_index_info', 'reportno'),
  ('app_check_index_info', 'customerid'),
  ('app_check_index_info', 'customername'),
  ('app_check_index_info', 'chineseid'),
  ('app_check_index_info', 'chinesename'),
  ('app_check_index_info', 'yesno'),
  ('app_check_index_info', 'remark'),
  ('app_check_index_info', 'inputtime'),
  ('app_check_index_info', 'indexobject'),
  ('app_check_index_info', 'isabnormal'),
  ('app_check_object_info', 'id'),
  ('app_check_object_info', 'reportno'),
  ('app_check_object_info', 'customerid'),
  ('app_check_object_info', 'customername'),
  ('app_check_object_info', 'objectname'),
  ('app_check_object_info', 'contractno'),
  ('app_check_object_info', 'indexno'),
  ('app_check_object_info', 'indexname'),
  ('app_check_object_info', 'indextype'),
  ('app_check_object_info', 'indexresult'),
  ('app_check_object_info', 'isabnormal'),
  ('app_check_object_info', 'redtextrequire'),
  ('app_check_object_info', 'inputtime'),
  ('app_check_opinion_info', 'id'),
  ('app_check_opinion_info', 'reportno'),
  ('app_check_opinion_info', 'customerid'),
  ('app_check_opinion_info', 'customername'),
  ('app_check_opinion_info', 'conditiondesc'),
  ('app_check_opinion_info', 'completestatus'),
  ('app_check_opinion_info', 'conditioninstruction'),
  ('app_check_opinion_info', 'realcompletetime'),
  ('app_check_opinion_info', 'itemcategory'),
  ('app_check_opinion_info', 'inputtime'),
  ('app_check_record_info', 'id'),
  ('app_check_record_info', 'reportno'),
  ('app_check_record_info', 'customerid'),
  ('app_check_record_info', 'customername'),
  ('app_check_record_info', 'checkintime'),
  ('app_check_record_info', 'checkinaddress'),
  ('app_check_record_info', 'visitobj'),
  ('app_check_record_info', 'checkinobj'),
  ('app_check_record_info', 'inputtime'),
  ('app_collateral_info', 'id'),
  ('app_collateral_info', 'reportno'),
  ('app_collateral_info', 'customerid'),
  ('app_collateral_info', 'customername'),
  ('app_collateral_info', 'owner'),
  ('app_collateral_info', 'clrtype'),
  ('app_collateral_info', 'clrname'),
  ('app_collateral_info', 'clrstatus'),
  ('app_collateral_info', 'valuationdate'),
  ('app_collateral_info', 'choicetypename'),
  ('app_collateral_info', 'evaluatevalue'),
  ('app_collateral_info', 'rightorder'),
  ('app_collateral_info', 'rightsum'),
  ('app_collateral_info', 'confirmdate'),
  ('app_collateral_info', 'inputtime'),
  ('app_collateral_info', 'clrid'),
  ('app_collateral_info', 'dyqdj'),
  ('app_collateral_info', 'yydj'),
  ('app_collateral_info', 'cfdj'),
  ('app_collateral_info', 'ygdj'),
  ('app_collateral_mortgage_info', 'id'),
  ('app_collateral_mortgage_info', 'reportno'),
  ('app_collateral_mortgage_info', 'customerid'),
  ('app_collateral_mortgage_info', 'customername'),
  ('app_collateral_mortgage_info', 'clrname'),
  ('app_collateral_mortgage_info', 'pledgeserialno'),
  ('app_collateral_mortgage_info', 'pledgeename'),
  ('app_collateral_mortgage_info', 'guaranteescope'),
  ('app_collateral_mortgage_info', 'pledgetypename'),
  ('app_collateral_mortgage_info', 'maxcreditoramt'),
  ('app_collateral_mortgage_info', 'startend'),
  ('app_collateral_mortgage_info', 'registertimestamp'),
  ('app_collateral_mortgage_info', 'inputtime'),
  ('app_collateral_mortgage_info', 'clrid'),
  ('app_collateral_restricted_right', 'id'),
  ('app_collateral_restricted_right', 'reportno'),
  ('app_collateral_restricted_right', 'customerid'),
  ('app_collateral_restricted_right', 'customername'),
  ('app_collateral_restricted_right', 'attachmentorg'),
  ('app_collateral_restricted_right', 'attachmenttypename'),
  ('app_collateral_restricted_right', 'inputtime'),
  ('app_collateral_restricted_right', 'clrid'),
  ('app_credit_approval_manage_req_info', 'id'),
  ('app_credit_approval_manage_req_info', 'reportno'),
  ('app_credit_approval_manage_req_info', 'customerid'),
  ('app_credit_approval_manage_req_info', 'customername'),
  ('app_credit_approval_manage_req_info', 'inputtime'),
  ('app_credit_approval_manage_req_info', 'swqno'),
  ('app_credit_approval_manage_req_info', 'pelativeserialno'),
  ('app_credit_approval_manage_req_info', 'checkdate'),
  ('app_credit_debt_detail', 'id'),
  ('app_credit_debt_detail', 'reportno'),
  ('app_credit_debt_detail', 'customerid'),
  ('app_credit_debt_detail', 'customername'),
  ('app_credit_debt_detail', 'querytime'),
  ('app_credit_debt_detail', 'zxreportno'),
  ('app_credit_debt_detail', 'debttype'),
  ('app_credit_debt_detail', 'orgcount'),
  ('app_credit_debt_detail', 'balance'),
  ('app_credit_debt_detail', 'inputtime'),
  ('app_credit_debt_detail', 'subjecttype'),
  ('app_credit_debt_detail', 'guarantorid'),
  ('app_credit_debt_detail', 'guarantorname'),
  ('app_credit_query_info', 'id'),
  ('app_credit_query_info', 'reportno'),
  ('app_credit_query_info', 'customerid'),
  ('app_credit_query_info', 'customername'),
  ('app_credit_query_info', 'querytime'),
  ('app_credit_query_info', 'zxreportno'),
  ('app_credit_query_info', 'loanquery12m'),
  ('app_credit_query_info', 'loanquery6m'),
  ('app_credit_query_info', 'loanquery3m'),
  ('app_credit_query_info', 'cardquery12m'),
  ('app_credit_query_info', 'cardquery6m'),
  ('app_credit_query_info', 'cardquery3m'),
  ('app_credit_query_info', 'selfquery1m'),
  ('app_credit_query_info', 'inputtime'),
  ('app_credit_query_info', 'guarantorid'),
  ('app_credit_query_info', 'guarantorname'),
  ('app_credit_report_info', 'id'),
  ('app_credit_report_info', 'reportno'),
  ('app_credit_report_info', 'customerid'),
  ('app_credit_report_info', 'customername'),
  ('app_credit_report_info', 'querytime'),
  ('app_credit_report_info', 'zxreportno'),
  ('app_credit_report_info', 'expiredate'),
  ('app_credit_report_info', 'overduetotal'),
  ('app_credit_report_info', 'attentioncreditbal'),
  ('app_credit_report_info', 'badcreditbal'),
  ('app_credit_report_info', 'attentionguaranteebal'),
  ('app_credit_report_info', 'badguaranteebal'),
  ('app_credit_report_info', 'guaranteeoverduetotal'),
  ('app_credit_report_info', 'guaranteeattentionbal'),
  ('app_credit_report_info', 'guaranteebadbal'),
  ('app_credit_report_info', 'extenddebtbal'),
  ('app_credit_report_info', 'restructuredebtbal'),
  ('app_credit_report_info', 'renewdebtbal'),
  ('app_credit_report_info', 'transferdebtbal'),
  ('app_credit_report_info', 'newolddebtbal'),
  ('app_credit_report_info', 'nonbankliabtotal'),
  ('app_credit_report_info', 'nonbankhighrateloan'),
  ('app_credit_report_info', 'inputtime'),
  ('app_credit_report_info', 'subjecttype'),
  ('app_credit_report_info', 'guarantorid'),
  ('app_credit_report_info', 'guarantorname'),
  ('app_credit_report_info', 'nonbankguaranteebal'),
  ('app_credit_report_info', 'workingcapitalloanbal'),
  ('app_credit_report_info', 'workingcapitalloan1ybal'),
  ('app_credit_report_info', 'loanbankorgcount'),
  ('app_credit_report_info', 'guaranteebankorgcount'),
  ('app_credit_report_info', 'creditshorttermdiff'),
  ('app_credit_report_info', 'creditlongtermdiff'),
  ('app_credit_report_info', 'creditdebtdeviation'),
  ('app_credit_report_info', 'guaranteenetasset'),
  ('app_credit_report_info', 'guaranteebalanceexbank'),
  ('app_credit_report_info', 'shorttermloanorgcount'),
  ('app_credit_report_info', 'midlongtermloanorgcount'),
  ('app_credit_report_info', 'revolvingoverdraftorgcount'),
  ('app_credit_report_info', 'discountorgcount'),
  ('app_credit_report_info', 'bankacceptancebillorgcount'),
  ('app_credit_report_info', 'letterofcreditorgcount'),
  ('app_credit_report_info', 'bankguaranteeorgcount'),
  ('app_credit_report_info', 'otherguaranteetradeorgcount'),
  ('app_credit_report_info', 'shorttermloanbal'),
  ('app_credit_report_info', 'midlongtermloanbal'),
  ('app_credit_report_info', 'revolvingoverdraftbal'),
  ('app_credit_report_info', 'discountbal'),
  ('app_credit_report_info', 'bankacceptancebillbal'),
  ('app_credit_report_info', 'letterofcreditbal'),
  ('app_credit_report_info', 'bankguaranteebal'),
  ('app_credit_report_info', 'otherguaranteetradebal'),
  ('app_credit_use_info', 'id'),
  ('app_credit_use_info', 'reportno'),
  ('app_credit_use_info', 'customerid'),
  ('app_credit_use_info', 'customername'),
  ('app_credit_use_info', 'creditsum'),
  ('app_credit_use_info', 'balance'),
  ('app_credit_use_info', 'exposureamount'),
  ('app_credit_use_info', 'limitbalance'),
  ('app_credit_use_info', 'groupamount'),
  ('app_credit_use_info', 'groupbalance'),
  ('app_credit_use_info', 'isgroup'),
  ('app_credit_use_info', 'groupname'),
  ('app_credit_use_info', 'creditdate'),
  ('app_credit_use_info', 'latestoverduedate'),
  ('app_credit_use_info', 'gdoverduecounts'),
  ('app_credit_use_info', 'ajoverduecounts'),
  ('app_credit_use_info', 'inputtime'),
  ('app_customer_info', 'id'),
  ('app_customer_info', 'reportno'),
  ('app_customer_info', 'customerid'),
  ('app_customer_info', 'customername'),
  ('app_customer_info', 'legalperson'),
  ('app_customer_info', 'registercapital'),
  ('app_customer_info', 'paidincapital'),
  ('app_customer_info', 'industrytype'),
  ('app_customer_info', 'holdtype'),
  ('app_customer_info', 'actualcontroller'),
  ('app_customer_info', 'officeaddress'),
  ('app_customer_info', 'businessscope'),
  ('app_customer_info', 'dangerlevel'),
  ('app_customer_info', 'warninglevel'),
  ('app_customer_info', 'isstateowned'),
  ('app_customer_info', 'islistedcompany'),
  ('app_customer_info', 'groupname'),
  ('app_customer_info', 'istechcompany'),
  ('app_customer_info', 'inputtime'),
  ('app_early_warning_info', 'id'),
  ('app_early_warning_info', 'reportno'),
  ('app_early_warning_info', 'customerid'),
  ('app_early_warning_info', 'customername'),
  ('app_early_warning_info', 'confirmtime'),
  ('app_early_warning_info', 'inputdate'),
  ('app_early_warning_info', 'approvestatusname'),
  ('app_early_warning_info', 'phaseopinion'),
  ('app_early_warning_info', 'endtime'),
  ('app_early_warning_info', 'risktasktype'),
  ('app_early_warning_info', 'tasktype'),
  ('app_early_warning_info', 'warnlevel'),
  ('app_early_warning_info', 'riskreason'),
  ('app_early_warning_info', 'inputtime'),
  ('app_early_warning_info', 'serialno'),
  ('app_early_warning_opinion_info', 'id'),
  ('app_early_warning_opinion_info', 'reportno'),
  ('app_early_warning_opinion_info', 'customerid'),
  ('app_early_warning_opinion_info', 'customername'),
  ('app_early_warning_opinion_info', 'serialno'),
  ('app_early_warning_opinion_info', 'confirmtime'),
  ('app_early_warning_opinion_info', 'seqno'),
  ('app_early_warning_opinion_info', 'activename'),
  ('app_early_warning_opinion_info', 'approveusername'),
  ('app_early_warning_opinion_info', 'approveorgname'),
  ('app_early_warning_opinion_info', 'warninglevelname'),
  ('app_early_warning_opinion_info', 'phaseopinion'),
  ('app_early_warning_opinion_info', 'endtime'),
  ('app_early_warning_opinion_info', 'inputtime'),
  ('app_early_warning_signal_info', 'id'),
  ('app_early_warning_signal_info', 'reportno'),
  ('app_early_warning_signal_info', 'customerid'),
  ('app_early_warning_signal_info', 'customername'),
  ('app_early_warning_signal_info', 'serialno'),
  ('app_early_warning_signal_info', 'riskmessage'),
  ('app_early_warning_signal_info', 'count'),
  ('app_early_warning_signal_info', 'readycount'),
  ('app_early_warning_signal_info', 'status'),
  ('app_early_warning_signal_info', 'warninglevel'),
  ('app_early_warning_signal_info', 'inputdate'),
  ('app_early_warning_signal_info', 'inputtime'),
  ('app_entrust_pay_info', 'id'),
  ('app_entrust_pay_info', 'reportno'),
  ('app_entrust_pay_info', 'customerid'),
  ('app_entrust_pay_info', 'customername'),
  ('app_entrust_pay_info', 'paymentmode'),
  ('app_entrust_pay_info', 'paydate'),
  ('app_entrust_pay_info', 'accountname'),
  ('app_entrust_pay_info', 'inputtime'),
  ('app_entrust_pay_info', 'payeecanceldate'),
  ('app_finance_index_info', 'id'),
  ('app_finance_index_info', 'reportno'),
  ('app_finance_index_info', 'customerid'),
  ('app_finance_index_info', 'customername'),
  ('app_finance_index_info', 'accountmonth'),
  ('app_finance_index_info', 'reportscope'),
  ('app_finance_index_info', 'sheetno'),
  ('app_finance_index_info', 'reportperiod'),
  ('app_finance_index_info', 'indextype'),
  ('app_finance_index_info', 'indexvalue'),
  ('app_finance_index_info', 'yoyvalue'),
  ('app_finance_index_info', 'changevalue'),
  ('app_finance_index_info', 'changerate'),
  ('app_finance_index_info', 'inputtime'),
  ('app_finance_index_info', 'currencyunit'),
  ('app_finance_index_info', 'finreportno'),
  ('app_finance_indicator_info', 'id'),
  ('app_finance_indicator_info', 'reportno'),
  ('app_finance_indicator_info', 'customerid'),
  ('app_finance_indicator_info', 'customername'),
  ('app_finance_indicator_info', 'finreportno'),
  ('app_finance_indicator_info', 'accountmonth'),
  ('app_finance_indicator_info', 'reportscope'),
  ('app_finance_indicator_info', 'reportperiod'),
  ('app_finance_indicator_info', 'auditflag'),
  ('app_finance_indicator_info', 'currency'),
  ('app_finance_indicator_info', 'monetaryunit'),
  ('app_finance_indicator_info', 'reportstatusname'),
  ('app_finance_indicator_info', 'reportstatus'),
  ('app_finance_indicator_info', 'inputtime'),
  ('app_finance_indicator_info', 'reporttypeno'),
  ('app_finance_indicator_info', 'reporttypename'),
  ('app_finance_indicator_info', 'sheetno'),
  ('app_finance_indicator_info', 'revenue'),
  ('app_finance_indicator_info', 'revenueyoy'),
  ('app_finance_indicator_info', 'netprofit'),
  ('app_finance_indicator_info', 'netprofityoy'),
  ('app_finance_indicator_info', 'paidincapital'),
  ('app_finance_indicator_info', 'totalequity'),
  ('app_finance_indicator_info', 'accountsreceivable'),
  ('app_finance_indicator_info', 'archangefromyearstart'),
  ('app_finance_indicator_info', 'archangefromyearstartrate'),
  ('app_finance_indicator_info', 'otherreceivable'),
  ('app_finance_indicator_info', 'orchangefromyearstart'),
  ('app_finance_indicator_info', 'orchangefromyearstartrate'),
  ('app_finance_indicator_info', 'arortotalassetratio'),
  ('app_finance_indicator_info', 'shortloan'),
  ('app_finance_indicator_info', 'shortloanchangefromyearstart'),
  ('app_finance_indicator_info', 'shortloanchangefromyearstartrate'),
  ('app_finance_indicator_info', 'longloan'),
  ('app_finance_indicator_info', 'longloanchangefromyearstart'),
  ('app_finance_indicator_info', 'longloanchangefromyearstartrate'),
  ('app_finance_indicator_info', 'longloanduewithin1y'),
  ('app_finance_indicator_info', 'salesloanratio'),
  ('app_finance_indicator_info', 'notespayable'),
  ('app_finance_indicator_info', 'notespayablechangefromyearstart'),
  ('app_finance_indicator_info', 'notespayablechangefromyearstartrate'),
  ('app_finance_indicator_info', 'otherpayable'),
  ('app_finance_indicator_info', 'otherpayablechangefromyearstart'),
  ('app_finance_indicator_info', 'otherpayablechangefromyearstartrate'),
  ('app_finance_indicator_info', 'sltotalloanyoy'),
  ('app_finance_indicator_info', 'aryoy'),
  ('app_finance_indicator_info', 'arturnoverdays'),
  ('app_finance_indicator_info', 'inventoryturnoverdays'),
  ('app_finance_indicator_info', 'inventoryyoy'),
  ('app_finance_indicator_info', 'accountspayable'),
  ('app_finance_indicator_info', 'inventory'),
  ('app_finance_indicator_info', 'debtratio'),
  ('app_finance_indicator_info', 'salesprofitratio'),
  ('app_finance_indicator_info', 'netprofitratio'),
  ('app_finance_indicator_info', 'guarantorid'),
  ('app_finance_indicator_info', 'guarantorname'),
  ('app_finance_indicator_info', 'subjecttype'),
  ('app_finance_report_info', 'id'),
  ('app_finance_report_info', 'reportno'),
  ('app_finance_report_info', 'customerid'),
  ('app_finance_report_info', 'customername'),
  ('app_finance_report_info', 'accountmonth'),
  ('app_finance_report_info', 'sheetno'),
  ('app_finance_report_info', 'reportscope'),
  ('app_finance_report_info', 'reportperiod'),
  ('app_finance_report_info', 'auditflag'),
  ('app_finance_report_info', 'currency'),
  ('app_finance_report_info', 'reportstatus'),
  ('app_finance_report_info', 'inputtime'),
  ('app_finance_report_info', 'currencyunit'),
  ('app_finance_report_info', 'finreportno'),
  ('app_graph_hit_info', 'id'),
  ('app_graph_hit_info', 'reportno'),
  ('app_graph_hit_info', 'customerid'),
  ('app_graph_hit_info', 'customername'),
  ('app_graph_hit_info', 'inputtime'),
  ('app_graph_hit_info', 'suspectedfundreturn'),
  ('app_graph_hit_info', 'suspectedloanpurposeabnormal'),
  ('app_graph_hit_info', 'suspectedborrowednameloan'),
  ('app_graph_hit_info', 'suspectedshellcompany'),
  ('app_graph_hit_info', 'suspectedguaranteecircle'),
  ('app_graph_hit_info', 'intrabankrelation'),
  ('app_graph_hit_info', 'entrustedpaymanytoone'),
  ('app_graph_hit_info', 'collateralsamecommunity'),
  ('app_gs_finance_data_info', 'id'),
  ('app_gs_finance_data_info', 'reportno'),
  ('app_gs_finance_data_info', 'customerid'),
  ('app_gs_finance_data_info', 'customername'),
  ('app_gs_finance_data_info', 'reportscope'),
  ('app_gs_finance_data_info', 'beforeyear'),
  ('app_gs_finance_data_info', 'lastyear'),
  ('app_gs_finance_data_info', 'thisyear'),
  ('app_gs_finance_data_info', 'gfrevenue'),
  ('app_gs_finance_data_info', 'lastyearrevenue'),
  ('app_gs_finance_data_info', 'beforeyearrevenue'),
  ('app_gs_finance_data_info', 'gfreceivable'),
  ('app_gs_finance_data_info', 'lastyearreceivable'),
  ('app_gs_finance_data_info', 'beforeyearreceivable'),
  ('app_gs_finance_data_info', 'gfpayable'),
  ('app_gs_finance_data_info', 'lastyearpayable'),
  ('app_gs_finance_data_info', 'beforeyearpayable'),
  ('app_gs_finance_data_info', 'gfinventory'),
  ('app_gs_finance_data_info', 'lastyearinventory'),
  ('app_gs_finance_data_info', 'beforeyearinventory'),
  ('app_gs_finance_data_info', 'inputtime'),
  ('app_gs_tax_sales_info', 'id'),
  ('app_gs_tax_sales_info', 'reportno'),
  ('app_gs_tax_sales_info', 'customerid'),
  ('app_gs_tax_sales_info', 'customername'),
  ('app_gs_tax_sales_info', 'inputtime'),
  ('app_gs_tax_sales_info', 'taxperiod'),
  ('app_gs_tax_sales_info', 'monthlytaxsales'),
  ('app_gs_tax_sales_info', 'totalsalestax'),
  ('app_gs_tax_sales_info', 'yoychange'),
  ('app_gs_tax_sales_info', 'yoyrate'),
  ('app_guarantor_credit_info', 'id'),
  ('app_guarantor_credit_info', 'reportno'),
  ('app_guarantor_credit_info', 'customerid'),
  ('app_guarantor_credit_info', 'customername'),
  ('app_guarantor_credit_info', 'guarantorname'),
  ('app_guarantor_credit_info', 'querytime'),
  ('app_guarantor_credit_info', 'zxreportno'),
  ('app_guarantor_credit_info', 'totalloanbal'),
  ('app_guarantor_credit_info', 'operateloanbal'),
  ('app_guarantor_credit_info', 'consumeloanbal'),
  ('app_guarantor_credit_info', 'houseloanbal'),
  ('app_guarantor_credit_info', 'otherloanbal'),
  ('app_guarantor_credit_info', 'totalloancount'),
  ('app_guarantor_credit_info', 'operateloancount'),
  ('app_guarantor_credit_info', 'consumeloancount'),
  ('app_guarantor_credit_info', 'houseloancount'),
  ('app_guarantor_credit_info', 'otherloancount'),
  ('app_guarantor_credit_info', 'bzcbal'),
  ('app_guarantor_credit_info', 'badbal'),
  ('app_guarantor_credit_info', 'loancurrentoverdue'),
  ('app_guarantor_credit_info', 'cardcurrentoverdue'),
  ('app_guarantor_credit_info', 'guaranteeoverdueamt'),
  ('app_guarantor_credit_info', 'nonbankguaranteebal'),
  ('app_guarantor_credit_info', 'nonbankhighrateloan'),
  ('app_guarantor_credit_info', 'guaranteeabnormalbal'),
  ('app_guarantor_credit_info', 'extendbal'),
  ('app_guarantor_credit_info', 'delaybal'),
  ('app_guarantor_credit_info', 'creditabnormalbal'),
  ('app_guarantor_credit_info', 'acctabnormalbal'),
  ('app_guarantor_credit_info', 'cardabnormalbal'),
  ('app_guarantor_credit_info', 'guaranteehkabnormalbal'),
  ('app_guarantor_credit_info', 'credituserate'),
  ('app_guarantor_credit_info', 'inputtime'),
  ('app_guarantor_credit_info', 'guarantorid'),
  ('app_guarantor_credit_info', 'nonbankliabtotal'),
  ('app_guarantor_credit_info', 'loanquery12m'),
  ('app_guarantor_credit_info', 'loanquery6m'),
  ('app_guarantor_credit_info', 'loanquery3m'),
  ('app_guarantor_credit_info', 'cardquery12m'),
  ('app_guarantor_credit_info', 'cardquery6m'),
  ('app_guarantor_credit_info', 'cardquery3m'),
  ('app_guarantor_credit_info', 'selfquery1m'),
  ('app_guarantor_info', 'id'),
  ('app_guarantor_info', 'reportno'),
  ('app_guarantor_info', 'customerid'),
  ('app_guarantor_info', 'customername'),
  ('app_guarantor_info', 'guarantorname'),
  ('app_guarantor_info', 'guarantortype'),
  ('app_guarantor_info', 'isstateowned'),
  ('app_guarantor_info', 'education'),
  ('app_guarantor_info', 'inputtime'),
  ('app_guarantor_info', 'guarantorid'),
  ('app_guarantor_info', 'subjecttype'),
  ('app_guarantor_info', 'zxreportnozx'),
  ('app_guarantor_info', 'zxreportnosq'),
  ('app_guarantor_info', 'zxreportnosx'),
  ('app_guofa_report_info', 'id'),
  ('app_guofa_report_info', 'reportno'),
  ('app_guofa_report_info', 'customerid'),
  ('app_guofa_report_info', 'customername'),
  ('app_guofa_report_info', 'datadate'),
  ('app_guofa_report_info', 'beforeyear'),
  ('app_guofa_report_info', 'lastyear'),
  ('app_guofa_report_info', 'thisyear'),
  ('app_guofa_report_info', 'gfrevenue'),
  ('app_guofa_report_info', 'lastyearrevenue'),
  ('app_guofa_report_info', 'beforeyearrevenue'),
  ('app_guofa_report_info', 'gfreceivable'),
  ('app_guofa_report_info', 'lastyearreceivable'),
  ('app_guofa_report_info', 'beforeyearreceivable'),
  ('app_guofa_report_info', 'gfpayable'),
  ('app_guofa_report_info', 'lastyearpayable'),
  ('app_guofa_report_info', 'beforeyearpayable'),
  ('app_guofa_report_info', 'gfinventory'),
  ('app_guofa_report_info', 'lastyearinventory'),
  ('app_guofa_report_info', 'beforeyearinventory'),
  ('app_guofa_report_info', 'inputtime'),
  ('app_ic_info', 'id'),
  ('app_ic_info', 'reportno'),
  ('app_ic_info', 'customerid'),
  ('app_ic_info', 'customername'),
  ('app_ic_info', 'iclegalperson'),
  ('app_ic_info', 'icregistercapital'),
  ('app_ic_info', 'icpaidincapital'),
  ('app_ic_info', 'icbeneficiaryname'),
  ('app_ic_info', 'icbeneficiarypercent'),
  ('app_ic_info', 'isstateowned'),
  ('app_ic_info', 'isfakestateowned'),
  ('app_ic_info', 'cancellationdate'),
  ('app_ic_info', 'inputtime'),
  ('app_ic_shareholder_info', 'id'),
  ('app_ic_shareholder_info', 'reportno'),
  ('app_ic_shareholder_info', 'customerid'),
  ('app_ic_shareholder_info', 'customername'),
  ('app_ic_shareholder_info', 'snapshot_type'),
  ('app_ic_shareholder_info', 'icshareholdername'),
  ('app_ic_shareholder_info', 'icstocknum'),
  ('app_ic_shareholder_info', 'icstockpercent'),
  ('app_ic_shareholder_info', 'icamount'),
  ('app_ic_shareholder_info', 'changetime'),
  ('app_ic_shareholder_info', 'percentbefore'),
  ('app_ic_shareholder_info', 'percentafter'),
  ('app_ic_shareholder_info', 'inputtime'),
  ('app_loan_plan_info', 'id'),
  ('app_loan_plan_info', 'reportno'),
  ('app_loan_plan_info', 'customerid'),
  ('app_loan_plan_info', 'customername'),
  ('app_loan_plan_info', 'producttype'),
  ('app_loan_plan_info', 'nextpaydate'),
  ('app_loan_plan_info', 'payprincipalamt'),
  ('app_loan_plan_info', 'payinterestamt'),
  ('app_loan_plan_info', 'payfineamt'),
  ('app_loan_plan_info', 'compoundinterest'),
  ('app_loan_plan_info', 'inputtime'),
  ('app_loan_receipt_info', 'id'),
  ('app_loan_receipt_info', 'reportno'),
  ('app_loan_receipt_info', 'customerid'),
  ('app_loan_receipt_info', 'customername'),
  ('app_loan_receipt_info', 'loanserialno'),
  ('app_loan_receipt_info', 'loanstatus'),
  ('app_loan_receipt_info', 'productname'),
  ('app_loan_receipt_info', 'producttype'),
  ('app_loan_receipt_info', 'purposename'),
  ('app_loan_receipt_info', 'balance'),
  ('app_loan_receipt_info', 'productbelongname'),
  ('app_loan_receipt_info', 'overduebalance'),
  ('app_loan_receipt_info', 'overdueinterestamt'),
  ('app_loan_receipt_info', 'isrestructed'),
  ('app_loan_receipt_info', 'extendbalance'),
  ('app_loan_receipt_info', 'restructedbalance'),
  ('app_loan_receipt_info', 'reorgtimes'),
  ('app_loan_receipt_info', 'reorgbalance'),
  ('app_loan_receipt_info', 'loanchangerptcounts'),
  ('app_loan_receipt_info', 'loanchangerptbalance'),
  ('app_loan_receipt_info', 'occurtype'),
  ('app_loan_receipt_info', 'isextend'),
  ('app_loan_receipt_info', 'inputtime'),
  ('app_loan_receipt_info', 'fixedassetloan'),
  ('app_loan_receipt_info', 'realestatedevloan'),
  ('app_loan_receipt_info', 'nextpaydate'),
  ('app_loan_receipt_info', 'payprincipalamt'),
  ('app_loan_receipt_info', 'payinterestamt'),
  ('app_loan_receipt_info', 'payfineamt'),
  ('app_loan_receipt_info', 'compoundinterest'),
  ('app_loan_receipt_info', 'businessrate'),
  ('app_loan_receipt_info', 'repaymentperiod'),
  ('app_loan_receipt_info', 'businesssum'),
  ('app_opinion_info', 'id'),
  ('app_opinion_info', 'reportno'),
  ('app_opinion_info', 'customerid'),
  ('app_opinion_info', 'customername'),
  ('app_opinion_info', 'phaseopinion'),
  ('app_opinion_info', 'endtime'),
  ('app_opinion_info', 'inputtime'),
  ('app_opinion_info', 'approveusername'),
  ('app_opinion_info', 'approveorgname'),
  ('app_payroll_stat_info', 'id'),
  ('app_payroll_stat_info', 'reportno'),
  ('app_payroll_stat_info', 'customerid'),
  ('app_payroll_stat_info', 'customername'),
  ('app_payroll_stat_info', 'statmonth'),
  ('app_payroll_stat_info', 'payrollcount'),
  ('app_payroll_stat_info', 'payrollamount'),
  ('app_payroll_stat_info', 'countmom'),
  ('app_payroll_stat_info', 'amountmom'),
  ('app_payroll_stat_info', 'countyoy'),
  ('app_payroll_stat_info', 'amountyoy'),
  ('app_payroll_stat_info', 'inputtime'),
  ('app_report_info', 'id'),
  ('app_report_info', 'reportno'),
  ('app_report_info', 'customerid'),
  ('app_report_info', 'customername'),
  ('app_report_info', 'reporttitle'),
  ('app_report_info', 'checktaskno'),
  ('app_report_info', 'reportdate'),
  ('app_report_info', 'reportstatus'),
  ('app_report_info', 'generatorname'),
  ('app_report_info', 'generatetime'),
  ('app_report_info', 'approvestatus'),
  ('app_report_info', 'approveopinion'),
  ('app_report_info', 'approvetime'),
  ('app_report_info', 'reporturl'),
  ('app_report_info', 'inputtime'),
  ('app_reputation_event_info', 'id'),
  ('app_reputation_event_info', 'reportno'),
  ('app_reputation_event_info', 'customerid'),
  ('app_reputation_event_info', 'customername'),
  ('app_reputation_event_info', 'subjecttype'),
  ('app_reputation_event_info', 'subjectname'),
  ('app_reputation_event_info', 'eventtime'),
  ('app_reputation_event_info', 'eventtype'),
  ('app_reputation_event_info', 'eventdesc'),
  ('app_reputation_event_info', 'inputtime'),
  ('app_reputation_event_info', 'eventtypecode'),
  ('app_reputation_event_info', 'eventtypeorder'),
  ('app_settle_account_info', 'id'),
  ('app_settle_account_info', 'reportno'),
  ('app_settle_account_info', 'customerid'),
  ('app_settle_account_info', 'customername'),
  ('app_settle_account_info', 'accountno'),
  ('app_settle_account_info', 'accountstatus'),
  ('app_settle_account_info', 'accountbalance'),
  ('app_settle_account_info', 'superviseflag'),
  ('app_settle_account_info', 'inputtime'),
  ('app_settle_asset_info', 'id'),
  ('app_settle_asset_info', 'reportno'),
  ('app_settle_asset_info', 'customerid'),
  ('app_settle_asset_info', 'customername'),
  ('app_settle_asset_info', 'frozenamount'),
  ('app_settle_asset_info', 'debitsamenametransferratio'),
  ('app_settle_asset_info', 'creditsamenametransferratio'),
  ('app_settle_asset_info', 'yearavgdeposit'),
  ('app_settle_asset_info', 'lastyearavgdeposit'),
  ('app_settle_asset_info', 'propertyincome'),
  ('app_settle_asset_info', 'propertyincomeyoy'),
  ('app_settle_asset_info', 'propertyincomesupervised'),
  ('app_settle_asset_info', 'electricfeeincome'),
  ('app_settle_asset_info', 'electricfeeyoy'),
  ('app_settle_asset_info', 'electricfeesupervised'),
  ('app_settle_asset_info', 'keywordcounterpartycreditamount'),
  ('app_settle_asset_info', 'keywordremarkcreditamount'),
  ('app_settle_asset_info', 'inputtime'),
  ('app_settle_counterparty_info', 'id'),
  ('app_settle_counterparty_info', 'reportno'),
  ('app_settle_counterparty_info', 'customerid'),
  ('app_settle_counterparty_info', 'customername'),
  ('app_settle_counterparty_info', 'counterpartyname'),
  ('app_settle_counterparty_info', 'direction'),
  ('app_settle_counterparty_info', 'amount'),
  ('app_settle_counterparty_info', 'rankno'),
  ('app_settle_counterparty_info', 'upstreamflag'),
  ('app_settle_counterparty_info', 'remark'),
  ('app_settle_counterparty_info', 'inputtime'),
  ('app_shareholder_info', 'id'),
  ('app_shareholder_info', 'reportno'),
  ('app_shareholder_info', 'customerid'),
  ('app_shareholder_info', 'customername'),
  ('app_shareholder_info', 'name'),
  ('app_shareholder_info', 'stock_num'),
  ('app_shareholder_info', 'amount'),
  ('app_shareholder_info', 'stock_percent'),
  ('app_shareholder_info', 'is_quoted'),
  ('app_shareholder_info', 'is_state_owned'),
  ('app_shareholder_info', 'is_fake_state_owned'),
  ('app_shareholder_info', 'is_listed_company'),
  ('app_shareholder_info', 'inputtime'),
  ('app_single_check_task_info', 'id'),
  ('app_single_check_task_info', 'reportno'),
  ('app_single_check_task_info', 'customerid'),
  ('app_single_check_task_info', 'customername'),
  ('app_single_check_task_info', 'itemcategory'),
  ('app_single_check_task_info', 'serialno'),
  ('app_single_check_task_info', 'creditno'),
  ('app_single_check_task_info', 'approvetextno'),
  ('app_single_check_task_info', 'startdate'),
  ('app_single_check_task_info', 'maturity'),
  ('app_single_check_task_info', 'groupname'),
  ('app_single_check_task_info', 'productname'),
  ('app_single_check_task_info', 'checkdate'),
  ('app_single_check_task_info', 'balance'),
  ('app_single_check_task_info', 'condition'),
  ('app_single_check_task_info', 'implementstatus'),
  ('app_single_check_task_info', 'extenddate'),
  ('app_single_check_task_info', 'opinion'),
  ('app_single_check_task_info', 'conditioninstruction'),
  ('app_single_check_task_info', 'creditapproveusername'),
  ('app_single_check_task_info', 'approveauthor'),
  ('app_single_check_task_info', 'operatebelongorgname'),
  ('app_single_check_task_info', 'operateorgname'),
  ('app_single_check_task_info', 'operateusername'),
  ('app_single_check_task_info', 'inputtime'),
  ('app_single_check_task_info', 'approvestatusname'),
  ('app_specific_loan_check_info', 'id'),
  ('app_specific_loan_check_info', 'reportno'),
  ('app_specific_loan_check_info', 'customerid'),
  ('app_specific_loan_check_info', 'customername'),
  ('app_specific_loan_check_info', 'objectname'),
  ('app_specific_loan_check_info', 'productname'),
  ('app_specific_loan_check_info', 'productbelongname'),
  ('app_specific_loan_check_info', 'contractno'),
  ('app_specific_loan_check_info', 'businesssum'),
  ('app_specific_loan_check_info', 'balance'),
  ('app_specific_loan_check_info', 'duebilltotalbusinesssum'),
  ('app_specific_loan_check_info', 'nominalbalancesum'),
  ('app_specific_loan_check_info', 'repaysum'),
  ('app_specific_loan_check_info', 'purpose'),
  ('app_specific_loan_check_info', 'vouchtype'),
  ('app_specific_loan_check_info', 'projectbegindate'),
  ('app_specific_loan_check_info', 'projectfinishdate'),
  ('app_specific_loan_check_info', 'ifbulid'),
  ('app_specific_loan_check_info', 'ifconstructionexpect'),
  ('app_specific_loan_check_info', 'ifgetpermission'),
  ('app_specific_loan_check_info', 'ifmatch'),
  ('app_specific_loan_check_info', 'ifopenaccount'),
  ('app_specific_loan_check_info', 'ifsign'),
  ('app_specific_loan_check_info', 'ifoverinvest'),
  ('app_specific_loan_check_info', 'overinvest'),
  ('app_specific_loan_check_info', 'ifoperate'),
  ('app_specific_loan_check_info', 'ifrunexpect'),
  ('app_specific_loan_check_info', 'schedulecheckcondition'),
  ('app_specific_loan_check_info', 'lastschedulecheckcondition'),
  ('app_specific_loan_check_info', 'capitalcheckcondition'),
  ('app_specific_loan_check_info', 'lastcapitalcheckcondition'),
  ('app_specific_loan_check_info', 'purchasecheckcondition'),
  ('app_specific_loan_check_info', 'lastpurchasecheckcondition'),
  ('app_specific_loan_check_info', 'runcheckcondition'),
  ('app_specific_loan_check_info', 'lastruncheckcondition'),
  ('app_specific_loan_check_info', 'supervisecheckcondition'),
  ('app_specific_loan_check_info', 'lastsupervisecheckcondition'),
  ('app_specific_loan_check_info', 'capitalfundinvoiced'),
  ('app_specific_loan_check_info', 'capitalfunduninvoiced'),
  ('app_specific_loan_check_info', 'capitalfundused'),
  ('app_specific_loan_check_info', 'loanfundinvoiced'),
  ('app_specific_loan_check_info', 'loanfunduninvoiced'),
  ('app_specific_loan_check_info', 'loanfundused'),
  ('app_specific_loan_check_info', 'otherfundinvoiced'),
  ('app_specific_loan_check_info', 'otherfunduninvoiced'),
  ('app_specific_loan_check_info', 'otherfundused'),
  ('app_specific_loan_check_info', 'totalinvestinvoiced'),
  ('app_specific_loan_check_info', 'totalinvestuninvoiced'),
  ('app_specific_loan_check_info', 'totalinvestused'),
  ('app_specific_loan_check_info', 'explain'),
  ('app_specific_loan_check_info', 'inputtime'),
  ('app_specific_loan_operate_check_info', 'id'),
  ('app_specific_loan_operate_check_info', 'reportno'),
  ('app_specific_loan_operate_check_info', 'customerid'),
  ('app_specific_loan_operate_check_info', 'customername'),
  ('app_specific_loan_operate_check_info', 'objectname'),
  ('app_specific_loan_operate_check_info', 'balance'),
  ('app_specific_loan_operate_check_info', 'businesssum'),
  ('app_specific_loan_operate_check_info', 'contractno'),
  ('app_specific_loan_operate_check_info', 'duebilltotalbusinesssum'),
  ('app_specific_loan_operate_check_info', 'expectation'),
  ('app_specific_loan_operate_check_info', 'expectation2'),
  ('app_specific_loan_operate_check_info', 'ifchange'),
  ('app_specific_loan_operate_check_info', 'ifdown'),
  ('app_specific_loan_operate_check_info', 'ifdownexplain'),
  ('app_specific_loan_operate_check_info', 'ifopenaccount'),
  ('app_specific_loan_operate_check_info', 'ifpledge'),
  ('app_specific_loan_operate_check_info', 'ifpledgeexplain'),
  ('app_specific_loan_operate_check_info', 'ifsign'),
  ('app_specific_loan_operate_check_info', 'ifsupervise'),
  ('app_specific_loan_operate_check_info', 'income'),
  ('app_specific_loan_operate_check_info', 'incomecompare'),
  ('app_specific_loan_operate_check_info', 'indexyear'),
  ('app_specific_loan_operate_check_info', 'indexyearcompare'),
  ('app_specific_loan_operate_check_info', 'lastincome'),
  ('app_specific_loan_operate_check_info', 'lastincomecompare'),
  ('app_specific_loan_operate_check_info', 'lastlesseecount'),
  ('app_specific_loan_operate_check_info', 'lastlesseecountcompare'),
  ('app_specific_loan_operate_check_info', 'lastoperatecdincomecondition'),
  ('app_specific_loan_operate_check_info', 'lastoperateincomecondition'),
  ('app_specific_loan_operate_check_info', 'lesseecount'),
  ('app_specific_loan_operate_check_info', 'lesseecountcompare'),
  ('app_specific_loan_operate_check_info', 'nominalbalancesum'),
  ('app_specific_loan_operate_check_info', 'operatecdincomecondition'),
  ('app_specific_loan_operate_check_info', 'operateincomecondition'),
  ('app_specific_loan_operate_check_info', 'productbelongname'),
  ('app_specific_loan_operate_check_info', 'productname'),
  ('app_specific_loan_operate_check_info', 'purpose'),
  ('app_specific_loan_operate_check_info', 'repaysum'),
  ('app_specific_loan_operate_check_info', 'signexplain'),
  ('app_specific_loan_operate_check_info', 'superviseexplain'),
  ('app_specific_loan_operate_check_info', 'vouchtype'),
  ('app_specific_loan_operate_check_info', 'inputtime'),
  ('app_specific_loan_project_check_info', 'id'),
  ('app_specific_loan_project_check_info', 'reportno'),
  ('app_specific_loan_project_check_info', 'customerid'),
  ('app_specific_loan_project_check_info', 'customername'),
  ('app_specific_loan_project_check_info', 'objectname'),
  ('app_specific_loan_project_check_info', 'balance'),
  ('app_specific_loan_project_check_info', 'businesssum'),
  ('app_specific_loan_project_check_info', 'capitalcheckcondition'),
  ('app_specific_loan_project_check_info', 'capitalfundinvoiced'),
  ('app_specific_loan_project_check_info', 'capitalfunduninvoiced'),
  ('app_specific_loan_project_check_info', 'capitalfundused'),
  ('app_specific_loan_project_check_info', 'contractno'),
  ('app_specific_loan_project_check_info', 'duebilltotalbusinesssum'),
  ('app_specific_loan_project_check_info', 'explain'),
  ('app_specific_loan_project_check_info', 'ifbuild'),
  ('app_specific_loan_project_check_info', 'ifconstructionexpect'),
  ('app_specific_loan_project_check_info', 'ifgetpermission'),
  ('app_specific_loan_project_check_info', 'ifmatch'),
  ('app_specific_loan_project_check_info', 'ifopenaccount'),
  ('app_specific_loan_project_check_info', 'ifoperate'),
  ('app_specific_loan_project_check_info', 'ifoverinvest'),
  ('app_specific_loan_project_check_info', 'ifrunexpect'),
  ('app_specific_loan_project_check_info', 'ifsign'),
  ('app_specific_loan_project_check_info', 'lastcapitalcheckcondition'),
  ('app_specific_loan_project_check_info', 'lastpurchasecheckcondition'),
  ('app_specific_loan_project_check_info', 'lastruncheckcondition'),
  ('app_specific_loan_project_check_info', 'lastschedulecheckcondition'),
  ('app_specific_loan_project_check_info', 'lastsupervisecheckcondition'),
  ('app_specific_loan_project_check_info', 'loanfundinvoiced'),
  ('app_specific_loan_project_check_info', 'loanfunduninvoiced'),
  ('app_specific_loan_project_check_info', 'loanfundused'),
  ('app_specific_loan_project_check_info', 'nominalbalancesum'),
  ('app_specific_loan_project_check_info', 'otherfundinvoiced'),
  ('app_specific_loan_project_check_info', 'otherfunduninvoiced'),
  ('app_specific_loan_project_check_info', 'otherfundused'),
  ('app_specific_loan_project_check_info', 'overinvest'),
  ('app_specific_loan_project_check_info', 'productbelongname'),
  ('app_specific_loan_project_check_info', 'productname'),
  ('app_specific_loan_project_check_info', 'projectbegindate'),
  ('app_specific_loan_project_check_info', 'projectfinishdate'),
  ('app_specific_loan_project_check_info', 'purchasecheckcondition'),
  ('app_specific_loan_project_check_info', 'purpose'),
  ('app_specific_loan_project_check_info', 'repaysum'),
  ('app_specific_loan_project_check_info', 'runcheckcondition'),
  ('app_specific_loan_project_check_info', 'schedulecheckcondition'),
  ('app_specific_loan_project_check_info', 'supervisecheckcondition'),
  ('app_specific_loan_project_check_info', 'totalinvestinvoiced'),
  ('app_specific_loan_project_check_info', 'totalinvestuninvoiced'),
  ('app_specific_loan_project_check_info', 'totalinvestused'),
  ('app_specific_loan_project_check_info', 'vouchtype'),
  ('app_specific_loan_project_check_info', 'inputtime'),
  ('app_top_five_updown_info', 'id'),
  ('app_top_five_updown_info', 'reportno'),
  ('app_top_five_updown_info', 'customerid'),
  ('app_top_five_updown_info', 'customername'),
  ('app_top_five_updown_info', 'supplier'),
  ('app_top_five_updown_info', 'suppliertype'),
  ('app_top_five_updown_info', 'suppliertypename'),
  ('app_top_five_updown_info', 'inputtime'),
  ('app_xd_shareholder_info', 'id'),
  ('app_xd_shareholder_info', 'reportno'),
  ('app_xd_shareholder_info', 'customerid'),
  ('app_xd_shareholder_info', 'customername'),
  ('app_xd_shareholder_info', 'name'),
  ('app_xd_shareholder_info', 'investmentprop'),
  ('app_xd_shareholder_info', 'relationship'),
  ('app_xd_shareholder_info', 'currencytype'),
  ('app_xd_shareholder_info', 'oughtsum'),
  ('app_xd_shareholder_info', 'investmentsum'),
  ('app_xd_shareholder_info', 'investdate'),
  ('app_xd_shareholder_info', 'inputuserid'),
  ('app_xd_shareholder_info', 'inputorgid'),
  ('app_xd_shareholder_info', 'inputtime'),
  ('report', 'id'),
  ('report', 'report_no'),
  ('report', 'customer_id'),
  ('report', 'customer_name'),
  ('report', 'check_task_no'),
  ('report', 'user_no'),
  ('report', 'version'),
  ('report', 'report_title'),
  ('report', 'report_type'),
  ('report', 'status'),
  ('report', 'fail_reason'),
  ('report', 'know_kit_task_id'),
  ('report', 'content_html'),
  ('report', 'data_snapshot'),
  ('report', 'created_at'),
  ('report', 'updated_at'),
  ('app_report_catalog', 'id'),
  ('app_report_catalog', 'catalogcode'),
  ('app_report_catalog', 'catalogname'),
  ('app_report_catalog', 'cataloglevel'),
  ('app_report_catalog', 'parentcode'),
  ('app_report_catalog', 'sortno'),
  ('app_report_catalog', 'isenabled'),
  ('app_report_catalog', 'inputtime'),
  ('app_report_content_block', 'id'),
  ('app_report_content_block', 'blockcode'),
  ('app_report_content_block', 'catalogcode'),
  ('app_report_content_block', 'filltype'),
  ('app_report_content_block', 'analysistype'),
  ('app_report_content_block', 'agentcode'),
  ('app_report_content_block', 'agentparams'),
  ('app_report_content_block', 'blockname'),
  ('app_report_content_block', 'titlelevel'),
  ('app_report_content_block', 'emptystrategy'),
  ('app_report_content_block', 'jumpanchorcode'),
  ('app_report_content_block', 'sortno'),
  ('app_report_content_block', 'isenabled'),
  ('app_report_content_block', 'inputtime'),
  ('app_report_content_instance', 'id'),
  ('app_report_content_instance', 'reportno'),
  ('app_report_content_instance', 'customerid'),
  ('app_report_content_instance', 'customername'),
  ('app_report_content_instance', 'blockcode'),
  ('app_report_content_instance', 'catalogcode'),
  ('app_report_content_instance', 'filltype'),
  ('app_report_content_instance', 'analysistype'),
  ('app_report_content_instance', 'agentcode'),
  ('app_report_content_instance', 'blockname'),
  ('app_report_content_instance', 'titlelevel'),
  ('app_report_content_instance', 'sortno'),
  ('app_report_content_instance', 'anchorcode'),
  ('app_report_content_instance', 'jumpanchorcode'),
  ('app_report_content_instance', 'content'),
  ('app_report_content_instance', 'inputtime'),
  ('app_report_ai_risk', 'id'),
  ('app_report_ai_risk', 'reportno'),
  ('app_report_ai_risk', 'customerid'),
  ('app_report_ai_risk', 'customername'),
  ('app_report_ai_risk', 'blockcode'),
  ('app_report_ai_risk', 'agentcode'),
  ('app_report_ai_risk', 'rulename'),
  ('app_report_ai_risk', 'riskdesc'),
  ('app_report_ai_risk', 'checkresult'),
  ('app_report_ai_risk', 'status'),
  ('app_report_ai_risk', 'jumpanchorcode'),
  ('app_report_ai_risk', 'sortno'),
  ('app_report_ai_risk', 'inputtime'),
  ('app_report_ai_analysis', 'id'),
  ('app_report_ai_analysis', 'reportno'),
  ('app_report_ai_analysis', 'checktaskno'),
  ('app_report_ai_analysis', 'customerid'),
  ('app_report_ai_analysis', 'customername'),
  ('app_report_ai_analysis', 'status'),
  ('app_report_ai_analysis', 'analysiscontent'),
  ('app_report_ai_analysis', 'summary'),
  ('app_report_ai_analysis', 'risklevel'),
  ('app_report_ai_analysis', 'lmcode'),
  ('app_report_ai_analysis', 'modelname'),
  ('app_report_ai_analysis', 'sourcesnapshot'),
  ('app_report_ai_analysis', 'promptsnapshot'),
  ('app_report_ai_analysis', 'operatorno'),
  ('app_report_ai_analysis', 'operatorname'),
  ('app_report_ai_analysis', 'costmillis'),
  ('app_report_ai_analysis', 'failreason'),
  ('app_report_ai_analysis', 'generatetime'),
  ('app_report_ai_analysis', 'inputtime'),
  ('app_report_prompt', 'id'),
  ('app_report_prompt', 'promptcode'),
  ('app_report_prompt', 'promptname'),
  ('app_report_prompt', 'scenetype'),
  ('app_report_prompt', 'systemprompt'),
  ('app_report_prompt', 'userprompttemplate'),
  ('app_report_prompt', 'isenabled'),
  ('app_report_prompt', 'remark'),
  ('app_report_prompt', 'inputtime'),
  ('app_report_prompt', 'updatetime'),
  ('app_report_warning_advice_batch', 'id'),
  ('app_report_warning_advice_batch', 'reportno'),
  ('app_report_warning_advice_batch', 'checktaskno'),
  ('app_report_warning_advice_batch', 'analysisid'),
  ('app_report_warning_advice_batch', 'customerid'),
  ('app_report_warning_advice_batch', 'customername'),
  ('app_report_warning_advice_batch', 'status'),
  ('app_report_warning_advice_batch', 'coretip'),
  ('app_report_warning_advice_batch', 'promptcode'),
  ('app_report_warning_advice_batch', 'lmcode'),
  ('app_report_warning_advice_batch', 'modelname'),
  ('app_report_warning_advice_batch', 'sourcesnapshot'),
  ('app_report_warning_advice_batch', 'promptsnapshot'),
  ('app_report_warning_advice_batch', 'operatorno'),
  ('app_report_warning_advice_batch', 'operatorname'),
  ('app_report_warning_advice_batch', 'costmillis'),
  ('app_report_warning_advice_batch', 'failreason'),
  ('app_report_warning_advice_batch', 'generatetime'),
  ('app_report_warning_advice_batch', 'inputtime'),
  ('app_report_warning_advice', 'id'),
  ('app_report_warning_advice', 'batchid'),
  ('app_report_warning_advice', 'reportno'),
  ('app_report_warning_advice', 'seqno'),
  ('app_report_warning_advice', 'warninglevel'),
  ('app_report_warning_advice', 'signaldesc'),
  ('app_report_warning_advice', 'triggercondition'),
  ('app_report_warning_advice', 'sourcetext'),
  ('app_report_warning_advice', 'riskdesc'),
  ('app_report_warning_advice', 'chapter'),
  ('app_report_warning_advice', 'status'),
  ('app_report_warning_advice', 'operatorno'),
  ('app_report_warning_advice', 'operatorname'),
  ('app_report_warning_advice', 'operatetime'),
  ('app_report_warning_advice', 'inputtime'),
  ('app_report_risk_edit_log', 'id'),
  ('app_report_risk_edit_log', 'checktaskno'),
  ('app_report_risk_edit_log', 'blockcode'),
  ('app_report_risk_edit_log', 'reportno'),
  ('app_report_risk_edit_log', 'blockname'),
  ('app_report_risk_edit_log', 'catalogcode'),
  ('app_report_risk_edit_log', 'customerid'),
  ('app_report_risk_edit_log', 'customername'),
  ('app_report_risk_edit_log', 'contentbefore'),
  ('app_report_risk_edit_log', 'contentafter'),
  ('app_report_risk_edit_log', 'operatorno'),
  ('app_report_risk_edit_log', 'operatorname'),
  ('app_report_risk_edit_log', 'inputtime')
)
SELECT e.tbl                              AS "表名",
       count(*)                           AS "缺失列数",
       string_agg(e.col, ', ' ORDER BY e.col) AS "缺失列"
  FROM expected e
  LEFT JOIN information_schema.columns c
    ON lower(c.table_name) = e.tbl
   AND lower(c.column_name) = e.col
   AND c.table_schema = current_schema()
 WHERE c.column_name IS NULL
   AND EXISTS (SELECT 1 FROM information_schema.tables t
                WHERE lower(t.table_name) = e.tbl AND t.table_schema = current_schema())
 GROUP BY e.tbl
 ORDER BY 2 DESC, 1;

-- =====================================================================
-- 附：把「列数不符」的表也看一眼（含只在库里多出来的列）
-- =====================================================================
-- WITH expected_cnt(tbl, cnt) AS (VALUES
--   ('app_capital_flow_info', 15),
--   ('app_check_index_info', 11),
--   ('app_check_object_info', 13),
--   ('app_check_opinion_info', 10),
--   ('app_check_record_info', 9),
--   ('app_collateral_info', 20),
--   ('app_collateral_mortgage_info', 14),
--   ('app_collateral_restricted_right', 8),
--   ('app_credit_approval_manage_req_info', 8),
--   ('app_credit_debt_detail', 13),
--   ('app_credit_query_info', 16),
--   ('app_credit_report_info', 52),
--   ('app_credit_use_info', 17),
--   ('app_customer_info', 19),
--   ('app_early_warning_info', 15),
--   ('app_early_warning_opinion_info', 14),
--   ('app_early_warning_signal_info', 12),
--   ('app_entrust_pay_info', 9),
--   ('app_finance_index_info', 16),
--   ('app_finance_indicator_info', 57),
--   ('app_finance_report_info', 14),
--   ('app_graph_hit_info', 13),
--   ('app_gs_finance_data_info', 21),
--   ('app_gs_tax_sales_info', 10),
--   ('app_guarantor_credit_info', 42),
--   ('app_guarantor_info', 14),
--   ('app_guofa_report_info', 21),
--   ('app_ic_info', 13),
--   ('app_ic_shareholder_info', 13),
--   ('app_loan_plan_info', 11),
--   ('app_loan_receipt_info', 33),
--   ('app_opinion_info', 9),
--   ('app_payroll_stat_info', 12),
--   ('app_report_info', 15),
--   ('app_reputation_event_info', 12),
--   ('app_settle_account_info', 9),
--   ('app_settle_asset_info', 18),
--   ('app_settle_counterparty_info', 11),
--   ('app_shareholder_info', 13),
--   ('app_single_check_task_info', 26),
--   ('app_specific_loan_check_info', 51),
--   ('app_specific_loan_operate_check_info', 42),
--   ('app_specific_loan_project_check_info', 51),
--   ('app_top_five_updown_info', 8),
--   ('app_xd_shareholder_info', 14),
--   ('report', 16),
--   ('app_report_catalog', 8),
--   ('app_report_content_block', 14),
--   ('app_report_content_instance', 16),
--   ('app_report_ai_risk', 13),
--   ('app_report_ai_analysis', 19),
--   ('app_report_prompt', 10),
--   ('app_report_warning_advice_batch', 19),
--   ('app_report_warning_advice', 15),
--   ('app_report_risk_edit_log', 13)
-- )
-- SELECT c.table_name AS "表名", count(*) AS "实际列数", e.cnt AS "期望列数"
--   FROM information_schema.columns c
--   JOIN expected_cnt e ON lower(c.table_name) = e.tbl
--  WHERE c.table_schema = current_schema()
--  GROUP BY c.table_name, e.cnt HAVING count(*) <> e.cnt ORDER BY 1;

