CREATE TABLE IF NOT EXISTS TASK_LOCK_INFO (
    TASK_NAME        VARCHAR2(64),
    INPUT_TIME       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    primary key (TASK_NAME)
);

COMMENT ON TABLE TASK_LOCK_INFO IS '应用层分布式锁表';
COMMENT ON COLUMN TASK_LOCK_INFO.TASK_NAME IS '主键：任务名称';
COMMENT ON COLUMN TASK_LOCK_INFO.INPUT_TIME IS '入库时间';